import processValidationSchemaCreateProcessJson from './processValidationSchemaCreateProcess.json';

import processValidationSchemaUpdateProcessJson from './processValidationSchemaUpdateProcess.json';

import processValidationSchemaReadProcessJson from './processValidationSchemaReadProcess.json';

import processValidationSchemaDeleteProcessJson from './processValidationSchemaDeleteProcess.json';

import threadValidationSchemaCreateThreadJson from './threadValidationSchemaCreateThread.json';

import threadValidationSchemaUpdateThreadJson from './threadValidationSchemaUpdateThread.json';

import threadValidationSchemaReadThreadJson from './threadValidationSchemaReadThread.json';

import threadValidationSchemaDeleteThreadJson from './threadValidationSchemaDeleteThread.json';

export const processValidationSchemaCreateProcess = processValidationSchemaCreateProcessJson;

export const processValidationSchemaUpdateProcess = processValidationSchemaUpdateProcessJson;

export const processValidationSchemaReadProcess = processValidationSchemaReadProcessJson;

export const processValidationSchemaDeleteProcess = processValidationSchemaDeleteProcessJson;

export const threadValidationSchemaCreateThread = threadValidationSchemaCreateThreadJson;

export const threadValidationSchemaUpdateThread = threadValidationSchemaUpdateThreadJson;

export const threadValidationSchemaReadThread = threadValidationSchemaReadThreadJson;

export const threadValidationSchemaDeleteThread = threadValidationSchemaDeleteThreadJson;
